#!/usr/bin/env bash
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
RPM1=$1
RPM2=$2
TMP1=$(mktemp -d)
TMP2=$(mktemp -d)
rpm2cpio $RPM1 | (cd $TMP1; cpio -idm --quiet)
rpm2cpio $RPM2 | (cd $TMP2; cpio -idm --quiet)
diff -uwr $TMP1 $TMP2 | sed "s@Only in $TMP1@Only in $RPM1:@g" | sed "s@Only in $TMP2@Only in $RPM2:@g"
rm -rf $TMP1
rm -rf $TMP2
